import jsPDF from "jspdf";
import type { AuditReport } from "./audit";

const A4_W = 210;
const A4_H = 297;
const MARGIN = 20;
const CONTENT_W = A4_W - MARGIN * 2;

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

const PRIMARY = hexToRgb("#4f46e5");
const DARK_BG = hexToRgb("#0a0a1a");
const MUTED = hexToRgb("#94a3b8");
const SUCCESS = hexToRgb("#22c55e");
const DANGER = hexToRgb("#ef4444");
const WHITE: [number, number, number] = [255, 255, 255];
const LIGHT_BG = hexToRgb("#141432");

interface ReportOptions {
  userName?: string;
  userEmail?: string;
  aiInsights?: string;
}

function addHeader(doc: jsPDF, pageNum: number, totalPages: number) {
  // Header bar
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, A4_W, 28, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...WHITE);
  doc.text("MetaClean", MARGIN, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Metadata Removal Report", A4_W / 2, 18, { align: "center" });

  doc.text(`Page ${pageNum} / ${totalPages}`, A4_W - MARGIN, 18, { align: "right" });
}

function addFooter(doc: jsPDF, date: string, userName: string) {
  const y = A4_H - 12;
  doc.setDrawColor(...MUTED);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y - 4, A4_W - MARGIN, y - 4);

  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text(`Generated by MetaClean • ${date}`, MARGIN, y);
  doc.text(`User: ${userName}`, A4_W / 2, y, { align: "center" });
  doc.text("Confidential", A4_W - MARGIN, y, { align: "right" });
}

function ensureSpace(doc: jsPDF, y: number, needed: number, date: string, userName: string, pages: { count: number }): number {
  if (y + needed > A4_H - 20) {
    addFooter(doc, date, userName);
    doc.addPage();
    pages.count++;
    addHeader(doc, pages.count, 0); // total pages patched later
    return 36;
  }
  return y;
}

export function generatePdfReport(
  reports: AuditReport[],
  options: ReportOptions = {}
): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });
  const fullDate = `${dateStr} ${timeStr}`;
  const userName = options.userName || options.userEmail || "Anonymous";
  const pages = { count: 1 };

  // ── Page 1: Cover / Summary ──
  addHeader(doc, 1, 0);

  let y = 44;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(...WHITE);
  doc.text("Metadata Cleaning Report", MARGIN, y);
  y += 12;

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text("Detailed audit of metadata fields removed during cleaning", MARGIN, y);
  y += 16;

  // Info box
  doc.setFillColor(...LIGHT_BG);
  doc.roundedRect(MARGIN, y, CONTENT_W, 32, 3, 3, "F");

  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  const infoY = y + 8;
  doc.text("Date:", MARGIN + 6, infoY);
  doc.text("User:", MARGIN + 6, infoY + 8);
  doc.text("Files Processed:", MARGIN + 6, infoY + 16);
  doc.text("Total Fields Removed:", MARGIN + CONTENT_W / 2, infoY + 16);

  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "bold");
  doc.text(fullDate, MARGIN + 30, infoY);
  doc.text(userName, MARGIN + 30, infoY + 8);
  doc.text(String(reports.length), MARGIN + 50, infoY + 16);

  const totalRemoved = reports.reduce((s, r) => s + r.summary.removed, 0);
  const totalKept = reports.reduce((s, r) => s + r.summary.kept, 0);
  doc.text(String(totalRemoved), MARGIN + CONTENT_W / 2 + 52, infoY + 16);

  y += 40;

  // Summary stats
  doc.setFillColor(SUCCESS[0], SUCCESS[1], SUCCESS[2]);
  doc.roundedRect(MARGIN, y, CONTENT_W / 2 - 4, 18, 2, 2, "F");
  doc.setFontSize(16);
  doc.setTextColor(...WHITE);
  doc.text(String(totalRemoved), MARGIN + (CONTENT_W / 2 - 4) / 2, y + 10, { align: "center" });
  doc.setFontSize(7);
  doc.text("Fields Removed", MARGIN + (CONTENT_W / 2 - 4) / 2, y + 15, { align: "center" });

  const rightX = MARGIN + CONTENT_W / 2 + 4;
  doc.setFillColor(...MUTED);
  doc.roundedRect(rightX, y, CONTENT_W / 2 - 4, 18, 2, 2, "F");
  doc.setFontSize(16);
  doc.setTextColor(...DARK_BG);
  doc.text(String(totalKept), rightX + (CONTENT_W / 2 - 4) / 2, y + 10, { align: "center" });
  doc.setFontSize(7);
  doc.text("Fields Kept", rightX + (CONTENT_W / 2 - 4) / 2, y + 15, { align: "center" });

  y += 28;

  // ── Per-file detail ──
  for (const report of reports) {
    y = ensureSpace(doc, y, 30, fullDate, userName, pages);

    // File header
    doc.setFillColor(...PRIMARY);
    doc.roundedRect(MARGIN, y, CONTENT_W, 10, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...WHITE);
    doc.text(report.filename, MARGIN + 4, y + 7);

    const sizeKb = (report.size / 1024).toFixed(1);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(`${report.type} • ${sizeKb} KB`, A4_W - MARGIN - 4, y + 7, { align: "right" });
    y += 14;

    // File summary
    doc.setFontSize(8);
    doc.setTextColor(...SUCCESS);
    doc.text(`✓ ${report.summary.removed} removed`, MARGIN + 4, y);
    doc.setTextColor(...MUTED);
    doc.text(`• ${report.summary.kept} kept`, MARGIN + 40, y);
    y += 6;

    // Table header
    y = ensureSpace(doc, y, 10, fullDate, userName, pages);
    doc.setFillColor(...LIGHT_BG);
    doc.rect(MARGIN, y, CONTENT_W, 7, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text("Field", MARGIN + 4, y + 5);
    doc.text("Original Value", MARGIN + 55, y + 5);
    doc.text("Status", A4_W - MARGIN - 4, y + 5, { align: "right" });
    y += 9;

    // Table rows
    for (const field of report.fields) {
      y = ensureSpace(doc, y, 7, fullDate, userName, pages);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(...WHITE);
      doc.text(field.name.slice(0, 30), MARGIN + 4, y + 4);

      doc.setTextColor(...MUTED);
      const val = field.originalValue.length > 40 ? field.originalValue.slice(0, 37) + "..." : field.originalValue;
      doc.text(val, MARGIN + 55, y + 4);

      if (field.status === "removed") {
        doc.setTextColor(...DANGER);
        doc.text("REMOVED", A4_W - MARGIN - 4, y + 4, { align: "right" });
      } else {
        doc.setTextColor(...SUCCESS);
        doc.text("KEPT", A4_W - MARGIN - 4, y + 4, { align: "right" });
      }

      // Subtle row divider
      doc.setDrawColor(30, 30, 60);
      doc.setLineWidth(0.1);
      doc.line(MARGIN + 2, y + 6, A4_W - MARGIN - 2, y + 6);
      y += 7;
    }

    y += 6;
  }

  // ── Patch page totals & add footers ──
  const totalPageCount = pages.count;
  for (let i = 1; i <= totalPageCount; i++) {
    doc.setPage(i);
    // Re-draw page number
    doc.setFillColor(...PRIMARY);
    doc.rect(A4_W - MARGIN - 30, 0, 50, 28, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...WHITE);
    doc.text(`Page ${i} / ${totalPageCount}`, A4_W - MARGIN, 18, { align: "right" });
    addFooter(doc, fullDate, userName);
  }

  // Download
  const filename = reports.length === 1
    ? `${reports[0].filename}_report.pdf`
    : `metaclean_report_${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
