import jsPDF from "jspdf";
import type { AuditReport } from "./audit";

const A4_W = 210;
const A4_H = 297;
const MARGIN = 16;
const CONTENT_W = A4_W - MARGIN * 2;

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

const PRIMARY = hexToRgb("#4f46e5");
const PRIMARY_LIGHT = hexToRgb("#6366f1");
const DARK_BG = hexToRgb("#0a0a1a");
const CARD_BG = hexToRgb("#141432");
const MUTED = hexToRgb("#94a3b8");
const SUCCESS = hexToRgb("#22c55e");
const DANGER = hexToRgb("#ef4444");
const WHITE: [number, number, number] = [255, 255, 255];
const AMBER = hexToRgb("#f59e0b");

interface ReportOptions {
  userName?: string;
  userEmail?: string;
  aiInsights?: string;
  isPWA?: boolean;
}

// ── Shared helpers ──

function setPage(doc: jsPDF, bg: [number, number, number] = DARK_BG) {
  doc.setFillColor(...bg);
  doc.rect(0, 0, A4_W, A4_H, "F");
}

function addBrandBar(doc: jsPDF, pageNum: number, totalPages: number) {
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, A4_W, 22, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...WHITE);
  doc.text("MetaClean", MARGIN, 15);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Metadata Removal Report", A4_W / 2, 15, { align: "center" });
  doc.text(`${pageNum} / ${totalPages}`, A4_W - MARGIN, 15, { align: "right" });
}

function addFooter(doc: jsPDF, date: string, userName: string) {
  const y = A4_H - 10;
  doc.setDrawColor(40, 40, 80);
  doc.setLineWidth(0.2);
  doc.line(MARGIN, y - 3, A4_W - MARGIN, y - 3);

  doc.setFontSize(6.5);
  doc.setTextColor(...MUTED);
  doc.text(`Generated by MetaClean • ${date}`, MARGIN, y);
  doc.text(`User: ${userName}`, A4_W / 2, y, { align: "center" });
  doc.text("Confidential", A4_W - MARGIN, y, { align: "right" });
}

function ensureSpace(doc: jsPDF, y: number, needed: number, pages: { count: number }): number {
  if (y + needed > A4_H - 16) {
    doc.addPage();
    pages.count++;
    setPage(doc);
    return 30; // header will be drawn in final pass
  }
  return y;
}

function drawRoundedBox(doc: jsPDF, x: number, y: number, w: number, h: number, color: [number, number, number]) {
  doc.setFillColor(...color);
  doc.roundedRect(x, y, w, h, 2, 2, "F");
}

function drawStatCard(doc: jsPDF, x: number, y: number, w: number, value: string, label: string, color: [number, number, number]) {
  drawRoundedBox(doc, x, y, w, 24, CARD_BG);
  // Accent bar
  doc.setFillColor(...color);
  doc.rect(x, y, 3, 24, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...color);
  doc.text(value, x + w / 2, y + 12, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text(label, x + w / 2, y + 20, { align: "center" });
}

// ── Main export ──

export function generatePdfReport(
  reports: AuditReport[],
  options: ReportOptions = {}
): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" });
  const fullDate = `${dateStr} ${timeStr}`;
  const userName = options.isPWA ? "Anonymous" : (options.userName || options.userEmail || "Anonymous");
  const pages = { count: 1 };

  const totalRemoved = reports.reduce((s, r) => s + r.summary.removed, 0);
  const totalKept = reports.reduce((s, r) => s + r.summary.kept, 0);
  const totalFields = totalRemoved + totalKept;
  const riskScore = totalFields > 0 ? Math.round((totalRemoved / totalFields) * 100) : 0;

  // ══════════════════════════════════
  //  PAGE 1 — COVER
  // ══════════════════════════════════
  setPage(doc);

  // Large brand
  let y = 50;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(32);
  doc.setTextColor(...PRIMARY_LIGHT);
  doc.text("MetaClean", A4_W / 2, y, { align: "center" });

  y += 10;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text("Metadata Removal Audit Report", A4_W / 2, y, { align: "center" });

  // Divider
  y += 12;
  doc.setDrawColor(...PRIMARY);
  doc.setLineWidth(0.5);
  doc.line(A4_W / 2 - 30, y, A4_W / 2 + 30, y);

  // Info
  y += 16;
  drawRoundedBox(doc, MARGIN, y, CONTENT_W, 36, CARD_BG);
  const iy = y + 10;
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text("Date:", MARGIN + 8, iy);
  doc.text("User:", MARGIN + 8, iy + 8);
  doc.text("Files Processed:", MARGIN + 8, iy + 16);
  doc.text("Total Fields Analyzed:", MARGIN + CONTENT_W / 2, iy + 16);

  doc.setTextColor(...WHITE);
  doc.setFont("helvetica", "bold");
  doc.text(fullDate, MARGIN + 30, iy);
  doc.text(userName, MARGIN + 30, iy + 8);
  doc.text(String(reports.length), MARGIN + 52, iy + 16);
  doc.text(String(totalFields), MARGIN + CONTENT_W / 2 + 54, iy + 16);

  // Summary cards
  y += 46;
  const cardW = (CONTENT_W - 12) / 3;
  drawStatCard(doc, MARGIN, y, cardW, String(totalRemoved), "Fields Removed", SUCCESS);
  drawStatCard(doc, MARGIN + cardW + 6, y, cardW, String(totalKept), "Fields Kept", MUTED);
  drawStatCard(doc, MARGIN + (cardW + 6) * 2, y, cardW, `${riskScore}%`, "Privacy Score", riskScore >= 70 ? SUCCESS : riskScore >= 40 ? AMBER : DANGER);

  // ══════════════════════════════════
  //  AI INSIGHTS (browser only)
  // ══════════════════════════════════
  if (options.aiInsights && !options.isPWA) {
    y += 36;
    y = ensureSpace(doc, y, 40, pages);

    drawRoundedBox(doc, MARGIN, y, CONTENT_W, 10, hexToRgb("#1e1b4b"));
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...PRIMARY_LIGHT);
    doc.text("AI Privacy Analysis", MARGIN + 6, y + 7);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text("Powered by AI", A4_W - MARGIN - 4, y + 7, { align: "right" });
    y += 14;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...WHITE);

    const insightLines = doc.splitTextToSize(options.aiInsights, CONTENT_W - 12);
    for (const line of insightLines) {
      y = ensureSpace(doc, y, 4.5, pages);
      doc.text(line, MARGIN + 6, y);
      y += 4;
    }
    y += 4;
  }

  // ══════════════════════════════════
  //  PER-FILE DETAILS
  // ══════════════════════════════════
  for (const report of reports) {
    // Start each file on new page if not enough space
    y += 8;
    y = ensureSpace(doc, y, 50, pages);

    // File header bar
    drawRoundedBox(doc, MARGIN, y, CONTENT_W, 12, PRIMARY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...WHITE);
    doc.text(report.filename, MARGIN + 5, y + 8);

    const sizeKb = (report.size / 1024).toFixed(1);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.text(`${report.type} • ${sizeKb} KB`, A4_W - MARGIN - 5, y + 8, { align: "right" });
    y += 16;

    // File summary
    doc.setFontSize(7.5);
    doc.setTextColor(...SUCCESS);
    doc.text(`✓ ${report.summary.removed} removed`, MARGIN + 5, y);
    doc.setTextColor(...MUTED);
    doc.text(`• ${report.summary.kept} kept`, MARGIN + 40, y);
    y += 7;

    // Table header
    y = ensureSpace(doc, y, 12, pages);
    drawRoundedBox(doc, MARGIN, y, CONTENT_W, 7, hexToRgb("#1e1b4b"));
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.setTextColor(...MUTED);
    const col1 = MARGIN + 4;
    const col2 = MARGIN + 46;
    const col3 = MARGIN + 100;
    const col4 = A4_W - MARGIN - 4;
    doc.text("Field", col1, y + 5);
    doc.text("Before", col2, y + 5);
    doc.text("After", col3, y + 5);
    doc.text("Status", col4, y + 5, { align: "right" });
    y += 9;

    // Table rows
    for (let fi = 0; fi < report.fields.length; fi++) {
      const field = report.fields[fi];
      y = ensureSpace(doc, y, 7, pages);

      // Alternate row bg
      if (fi % 2 === 0) {
        doc.setFillColor(20, 20, 50);
        doc.rect(MARGIN, y - 1, CONTENT_W, 7, "F");
      }

      doc.setFont("helvetica", "normal");
      doc.setFontSize(6.5);
      doc.setTextColor(...WHITE);
      doc.text(field.name.slice(0, 24), col1, y + 4);

      doc.setTextColor(...MUTED);
      const beforeVal = field.originalValue.length > 28 ? field.originalValue.slice(0, 25) + "…" : field.originalValue;
      doc.text(beforeVal, col2, y + 4);

      const afterVal = field.afterValue
        ? (field.afterValue.length > 28 ? field.afterValue.slice(0, 25) + "…" : field.afterValue)
        : "—";
      doc.text(afterVal, col3, y + 4);

      if (field.status === "removed") {
        doc.setFillColor(239, 68, 68, 0.15);
        doc.setTextColor(...DANGER);
        doc.text("REMOVED", col4, y + 4, { align: "right" });
      } else {
        doc.setTextColor(...SUCCESS);
        doc.text("KEPT", col4, y + 4, { align: "right" });
      }

      y += 7;
    }

    y += 4;
  }

  // ══════════════════════════════════
  //  PATCH: Headers, Footers, Page #
  // ══════════════════════════════════
  const totalPageCount = pages.count;
  for (let i = 1; i <= totalPageCount; i++) {
    doc.setPage(i);
    addBrandBar(doc, i, totalPageCount);
    addFooter(doc, fullDate, userName);
  }

  // Download
  const filename = reports.length === 1
    ? `${reports[0].filename}_report.pdf`
    : `metaclean_report_${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
